### ISSUE TITLE
API Design: Should transcripts be their own endpoint or should they be denormalized as a part of the moment endpoint?

### ISSUE THREAD

**Issue by austinpray** [UTD-CRSS/API.exploreapollo.org#6]
So we have this view:

![2015-10-21 22-59-51](https://cloud.githubusercontent.com/assets/2192970/10656718/7ff30036-7847-11e5-9ddd-e0850f9c918d.jpg)

The only problem here is gonna be the transcripts. There are 2 ways I can think of to feed this view. Things to consider:

- This view could have 10 hours of audio, so 10 hours of transcript text. Do we need to break that up into multiple calls? Maybe gzipped it's not a big deal? Is this a big deal?

Based on these two problems we have two solutions I can think of:

## Denormalize Transcripts as a Part of the "/moments" endpoint

`/api/moments/1`

```js
{
  "title": "Moon Landing",
  "audioUrl": "...",
  "body": {},
  "transcripts": [
    {"id": 1, "speaker": "Buzz", "message": "Hello", "startTime": "00:00:01", channel: 1},
    {"id": 2, "speaker": "Buzz", "message": "World", "startTime": "00:00:02", channel: 1},
    {"id": 3, "speaker": "Neil", "message": "Weee", "startTime": "00:00:02", channel: 2},
    // wash rinse repeat
  ]
}
```

## Separate Transcripts Endpoint

`/api/transcripts?channel=1&channel=2&startTime=00:00:00&endTime=00:01:00`

```js
{
  "transcripts": [
    {"id": 1, "speaker": "Buzz", "message": "Hello", "startTime": "00:00:01", channel: 1},
    {"id": 2, "speaker": "Buzz", "message": "World", "startTime": "00:00:02", channel: 1},
    {"id": 3, "speaker": "Neil", "message": "Weee", "startTime": "00:00:02", channel: 2},
  ]
}
```

### Or 

```js
{
  "title": "Moon Landing",
  "audioUrl": "...",
  "body": {},
  "transcripts": [
    {
      "url": "/api/transcripts?channel=1&channel=2&startTime=00:00:00&endTime=00:01:00",
      "startTime": "00:00:00",
      "endTime": "00:01:00"
    },
    {
      "url": "/api/transcripts?channel=1&channel=2&startTime=00:01:00&endTime=00:02:00",
      "startTime": "00:01:00",
      "endTime": "00:02:00"
    }
  ]
}
```

## What should we do?

I think it really boils down running tests to determine if normalizing the transcripts into a separate endpoint is over engineering or not.

If someone wants to just math out the worst-case scenario:

Moment with all channels and 10 hours of mission audio:

30 Channels,
10 hours of audio
1 transcript message per second of channel audio

Or more realistically:

1 Channel
10 hours of audio
1 transcript message per second of channel audio
Assuming a transcript message is about a tweet at 140 chars -> 140 bytes UTF-8
http://www.wolframalpha.com/input/?i=10+hours+at+140+bytes+per+second

![image](https://cloud.githubusercontent.com/assets/2192970/10657253/06b4c798-784e-11e5-8082-064d9afa6e63.png)

So worst-case scenario is 5 MB. That's not terrible. Gzip might eat that for breakfast. Might have to use a streaming json decoder though.

For 30 mins: http://www.wolframalpha.com/input/?i=30+minutes+at+140+bytes+per+second
252 kB isn't that bad. 

Is there anything I am not considering?

**Comment by austinpray** [comment]
A hugely persuasive argument for splitting transcripts into their own endpoint might be that including all of those transcripts denormalized into the the response could be subject to a lot of overfetching in cases where you call the endpoint just to get the title of a moment or something.

**Comment by nathanielks** [comment]
I'm personally a fan of the endpoint giving you a great starting point and then fetching anything you need after that based on demand. Perhaps you could provide the first minute or five minutes of transcripts with the moments endpoint, then when you've determined the client has 1) stayed on the page and 2) is actually interested in listening to more, you can fetch the additional data.

**Comment by nathanielks** [comment]
Perhaps as well you could find out what the mean clip length is and spit out the transcripts that will cover the majority of your use case, then fetch additional past that (once the client has determined the person is actually listening to the stream and not checking out the first 15 seconds or so)

**Comment by VictorK1902** [comment]
I kinda lean on having a separate end-point for transcript. We could always slice the entire thing to chunks and load one by one after every time interval. That way we dont have to have everything ready to display and then the user decides to leave after 30s into the moment.

**Comment by JamieCrisman** [comment]
I'd say have it separate because transcripts would likely be something we'd be streaming. It's a continuous data flow. I don't think the moment data (minus the transcript) is going to be a huge flow of information.

**Comment by VictorK1902** [comment]
So should we confirm? I kinda want to have this ready and make changes for tomorrow meeting

**Comment by austinpray** [comment]
Yeah let's just roll with a separate endpoint
